"""Generation strategies (the behaviour policies pi_b) and the on-disk layout that
carries them.

WHAT CHANGED (2026-09-06)
The C++ generator grew `--dataset_generation {BFS,DFS,S_DFS,HFS}` (commit b71b992).
Before it, every table was a stochastic-DFS sample and the four behaviour policies
were SYNTHESISED over that one tree (`policies.py`: bfs/dfs/hfs_oracle/random rank
the same DFS tree by depth / -depth / delta / U(0,1)). Now each behaviour policy has
its OWN tree, generated by the real search, so:

    one reconstructed tree PER (instance, strategy)   -- `tree.load_tree_instance`
    fringes are rolled inside THAT tree                -- `env.FringeEnv`
    the behaviour ranking is the generator's own       -- `policies.TRACE_POLICY`
    expansion order, recovered from the table

The user decides which pi_b enter training by deciding which strategies to
GENERATE (`create_all_training_data.py --dataset-generation ...`) and, optionally,
by restricting further at training time (`train_models.py --strategies ...`). A
strategy that was asked for but not generated is an ERROR here, never a silent
fallback to whatever is on disk.

ON-DISK LAYOUT (owned by scripts/gnn_exp/create_training_data.py)

    <exp>/_models/<domain>/training_data/<STRAT>/<instance>/<instance>_<TOKEN>_depth_<D>.csv
    <exp>/_models/<domain>/training_data/<instance>/<instance>_depth_<D>.csv        (LEGACY)

`<STRAT>` is the C++ enum spelling (BFS, DFS, S_DFS, HFS). `<TOKEN>` is what the C++
embeds in the CSV name: BFS / DFS / S_DFS / HFS_SUBGOALS_ (the heuristic is appended,
so the HFS token ends in `_` and the file reads `..._HFS_SUBGOALS__depth_25.csv` with
a DOUBLE underscore). Legacy tables carry no token: they predate the flag, so they
are S_DFS by construction (the DFS worker was the only generator).

WHY THE STRATEGY IS A DIRECTORY LEVEL AND NOT JUST THE FILE NAME
`create_training_data.py` moves each C++ run to `<target>/<instance>/` and rmtree's
whatever is there, and the DOT files inside `RawFiles/` are numbered per run
(`000001.dot`, ...). Two strategies in one instance folder would overwrite each
other's DOTs while both CSVs kept pointing at them. The strategy level keeps every
run self-contained.

The instance name is ALWAYS the CSV's parent directory (that is what `config_of`,
`expected_optimal` and the problem-file lookup parse), never the file name.

THIS MODULE OWNS NO GENERATION PARAMETER. It names strategies and finds tables.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

# Canonical (Python-side) ids, lowercase. Order = the order results are reported in.
STRATEGIES: Tuple[str, ...] = ("bfs", "dfs", "s_dfs", "hfs")

# The C++ enum spelling == the directory name on disk.
_DIR_NAME = {"bfs": "BFS", "dfs": "DFS", "s_dfs": "S_DFS", "hfs": "HFS"}
_FROM_DIR = {v: k for k, v in _DIR_NAME.items()}

# What a legacy (token-less) table is. Not a default in the "second opinion" sense:
# before b71b992 the DFS worker was the ONLY generator, so a token-less table cannot
# be anything else.
LEGACY_STRATEGY = "s_dfs"

# Separator between instance and strategy in a tree name. Chosen so that
# `name.rsplit("__pl_", 1)[0]` (selection.config_of) and the `__pl_(\d+)` regex
# (usability.expected_optimal) keep working on the composite name.
NAME_SEP = "@"

_TOKEN_RE = re.compile(r"_(BFS|DFS|S_DFS|HFS(?:_[A-Za-z0-9]+)*?_?)_depth_\d+\.csv$")
_DEPTH_RE = re.compile(r"_depth_(\d+)\.csv$")


def normalize_strategy(value: str) -> str:
    """User spellings (S-DFS, s_dfs, bfs, HFS ...) -> canonical id. Raises on junk."""
    v = str(value).strip().lower().replace("-", "_")
    if v not in STRATEGIES:
        raise ValueError(
            f"unknown generation strategy {value!r}; expected one of "
            f"{list(STRATEGIES)} (case-insensitive, '-' == '_')"
        )
    return v


def dir_name(strategy: str) -> str:
    """Canonical id -> the directory the generator writes (== C++ enum spelling)."""
    return _DIR_NAME[normalize_strategy(strategy)]


def strategy_from_dir_name(name: str) -> Optional[str]:
    """`BFS` -> `bfs`; anything that is not a strategy directory -> None."""
    return _FROM_DIR.get(name)


def strategy_from_csv_name(filename: str) -> Optional[str]:
    """Parse the token the C++ embeds in the CSV name.

    `CC_2_2_3__pl_4_BFS_depth_20.csv`            -> `bfs`
    `CC_2_2_3__pl_4_S_DFS_depth_20.csv`          -> `s_dfs`
    `CC_2_2_3__pl_4_HFS_SUBGOALS__depth_20.csv`  -> `hfs`
    `CC_2_2_3__pl_4_depth_25.csv`                -> None   (legacy, token-less)
    """
    m = _TOKEN_RE.search(Path(filename).name)
    if not m:
        return None
    tok = m.group(1)
    if tok.startswith("HFS"):
        return "hfs"
    return _FROM_DIR[tok]


def depth_from_csv_name(filename: str) -> Optional[int]:
    m = _DEPTH_RE.search(Path(filename).name)
    return int(m.group(1)) if m else None


def strategy_of_table(csv_path: str | Path) -> str:
    """The strategy a table was generated with, from its location and its name.

    The directory level is authoritative when present (`.../training_data/BFS/<inst>/`);
    the file token must agree with it. Without a strategy directory the token decides,
    and a token-less table is LEGACY_STRATEGY.
    """
    p = Path(csv_path)
    from_name = strategy_from_csv_name(p.name)
    from_dir = strategy_from_dir_name(p.parent.parent.name) if len(p.parents) >= 2 else None
    if from_dir is not None:
        if from_name is not None and from_name != from_dir:
            raise ValueError(
                f"{p}: sits under a {dir_name(from_dir)}/ directory but its name says "
                f"{dir_name(from_name)} -- the table was moved between strategy folders. "
                f"Refusing to guess which is right."
            )
        return from_dir
    return from_name if from_name is not None else LEGACY_STRATEGY


def tree_name(instance: str, strategy: str) -> str:
    """`CC_2_2_3__pl_4`, `bfs` -> `CC_2_2_3__pl_4@bfs`. One tree per (instance, pi_b)."""
    return f"{instance}{NAME_SEP}{normalize_strategy(strategy)}"


def split_tree_name(name: str) -> Tuple[str, Optional[str]]:
    """Inverse of tree_name; a bare instance name yields (name, None)."""
    if NAME_SEP in name:
        inst, strat = name.rsplit(NAME_SEP, 1)
        return inst, strat
    return name, None


# ----------------------------------------------------------------------------
# discovery
# ----------------------------------------------------------------------------

def _tables_in(inst_dir: Path) -> List[Path]:
    return sorted(p for p in inst_dir.glob("*_depth_*.csv") if p.is_file())


def discover_tables(data_dir: str | Path) -> Dict[str, Dict[str, Path]]:
    """{instance: {strategy: csv_path}} for everything under a training_data dir.

    Handles BOTH layouts (strategy level present or legacy flat) but refuses a MIX
    of the two, an instance folder with two tables for the same strategy, and a
    table whose folder and name disagree -- every one of those is a generation-side
    accident that must not be papered over by "take the first match" (which is
    exactly what the previous `matches[0]` did: `_BFS_` sorts before `_S_DFS_`, so a
    folder holding both would silently have trained on BFS).
    """
    root = Path(data_dir)
    out: Dict[str, Dict[str, Path]] = {}
    if not root.is_dir():
        return out
    subdirs = sorted(p for p in root.iterdir() if p.is_dir())
    strat_dirs = [p for p in subdirs if strategy_from_dir_name(p.name) is not None]
    inst_dirs = [p for p in subdirs if strategy_from_dir_name(p.name) is None]
    if strat_dirs and inst_dirs:
        # An instance dir at top level next to strategy dirs: legacy + new mixed.
        mixed_inst = [p.name for p in inst_dirs if _tables_in(p)]
        if mixed_inst:
            raise ValueError(
                f"{root}: mixes the strategy layout ({[p.name for p in strat_dirs]}) with "
                f"legacy instance folders at top level ({mixed_inst}). Move the legacy "
                f"folders under {dir_name(LEGACY_STRATEGY)}/ (they are S_DFS) or delete them."
            )

    def _add(inst: str, strat: str, csv: Path) -> None:
        slot = out.setdefault(inst, {})
        if strat in slot:
            raise ValueError(
                f"instance {inst!r} has two tables for strategy {dir_name(strat)}: "
                f"{slot[strat]} and {csv}. One tree per (instance, strategy); remove one."
            )
        slot[strat] = csv

    for sd in strat_dirs:
        strat = strategy_from_dir_name(sd.name)
        for inst_dir in sorted(p for p in sd.iterdir() if p.is_dir()):
            for csv in _tables_in(inst_dir):
                got = strategy_of_table(csv)          # validates dir-vs-token agreement
                assert got == strat
                _add(inst_dir.name, strat, csv)
    for inst_dir in inst_dirs:
        for csv in _tables_in(inst_dir):
            _add(inst_dir.name, strategy_of_table(csv), csv)
    return out


def available_strategies(tables: Dict[str, Dict[str, Path]]) -> List[str]:
    found = {s for per in tables.values() for s in per}
    return [s for s in STRATEGIES if s in found]


def select_tables(
    tables: Dict[str, Dict[str, Path]],
    strategies: Optional[Iterable[str]] = None,
    *,
    verbose: bool = True,
) -> List[Path]:
    """The CSVs to train on, in (instance, strategy) order.

    `strategies=None` -> every strategy found on disk. Otherwise every requested
    strategy must exist for at least one instance (else ValueError -- the user asked
    for a pi_b that was never generated), and an instance lacking one of the
    requested strategies is reported and skipped for THAT strategy only.
    """
    avail = available_strategies(tables)
    if strategies is None:
        wanted = avail
    else:
        wanted = [normalize_strategy(s) for s in strategies]
        missing = [s for s in wanted if s not in avail]
        if missing:
            raise ValueError(
                f"requested strategies {[dir_name(s) for s in missing]} were never "
                f"generated here; available: {[dir_name(s) for s in avail] or 'none'}. "
                f"Generate them (create_all_training_data.py --dataset-generation ...) "
                f"or drop them from --strategies."
            )
    out: List[Path] = []
    for inst in sorted(tables):
        per = tables[inst]
        for s in wanted:
            if s in per:
                out.append(per[s])
            elif verbose:
                print(f"[strategies] {inst}: no {dir_name(s)} table -- skipped for that "
                      f"strategy (has {[dir_name(x) for x in per]})")
    return out


def tables_under(data_dir: str | Path, strategies: Optional[Iterable[str]] = None,
                 *, verbose: bool = True) -> List[Path]:
    """discover + select in one call."""
    return select_tables(discover_tables(data_dir), strategies, verbose=verbose)


def describe(tables: Dict[str, Dict[str, Path]]) -> str:
    """One line per instance: which strategies it has."""
    lines = []
    for inst in sorted(tables):
        lines.append(f"  {inst:28} {' '.join(dir_name(s) for s in STRATEGIES if s in tables[inst])}")
    return "\n".join(lines)


def parse_strategy_list(values: Sequence[str]) -> List[str]:
    """CLI helper: ['all'] or ['BFS,HFS'] or ['bfs', 's-dfs'] -> canonical ids, in
    STRATEGIES order, deduplicated."""
    flat: List[str] = []
    for v in values:
        flat.extend(x for x in str(v).replace(",", " ").split() if x)
    if any(x.lower() == "all" for x in flat):
        return list(STRATEGIES)
    got = {normalize_strategy(x) for x in flat}
    return [s for s in STRATEGIES if s in got]
