"""Generated cloud-scheduling instances (tier 2-intermediate).

Template: the benchmark generator's output (cloud-NN-lenLL). An instance is a
list of tasks, each starting in a phase -- fresh (not scheduled, not
executing; its plan needs 6 actions), sched (scheduled; 4) or exec
(executing; 3) -- each owned by one tenant; the goal asks completion,
validation, scheduler knowledge, owner knowledge and privacy (no other tenant
knows), and the minimal plan length is the sum over the tasks. The benchmark
only uses 'fresh first, at most the last task not fresh' with two tenants.
Varied here: phase combinations, the number of tenants (2 or 3) and the task
ownership. Deterministic (no randomness).

Two named instance sets (numbering continues across them):
  v1 (g-cloud-01..10): mixed phases, 2-3 tenants.
  v2 (g-cloud-11..25): 3-task training shapes with short phases (11-16),
      fresh-first 2- and 3-task shapes as the benchmark's training problems,
      with changed ownership (17-21), and fresh-first 3-task validation
      shapes (22-25). The final per-domain cloud-scheduling model trains on
      g-cloud-17/18/19 and validates on g-cloud-22/23 (split.csv).
"""

from . import Problem

TIER, FAMILY = '2-intermediate', 'cloud-scheduling'
# First line of every file (a comment: it is not part of any planner state).
HEADER = ';; Generated by gnn_epddl.generators.cloud_scheduling (training/validation instance, not a benchmark problem)'
COST = {'fresh': 6, 'sched': 4, 'exec': 3}
# (phases, number of tenants, owner index per task (1-based)); the first number of each block is its first index
SETS = {
    'v1': [(1, [
        (['exec', 'exec'], 2, [1, 2]),
        (['sched', 'sched'], 2, [1, 2]),
        (['fresh', 'exec'], 3, [1, 2]),
        (['sched', 'fresh'], 2, [2, 1]),
        (['fresh', 'sched'], 3, [1, 3]),
        (['fresh', 'fresh'], 3, [1, 2]),
        (['fresh', 'fresh', 'exec'], 3, [1, 2, 3]),
        (['exec', 'fresh', 'fresh'], 2, [1, 2, 1]),
        (['fresh', 'sched', 'fresh'], 2, [2, 1, 2]),
        (['fresh', 'fresh', 'sched'], 3, [1, 1, 2]),
    ])],
    'v2': [(11, [   # 3 tasks, short phases (exec/sched, at most one fresh task)
        (['exec', 'exec', 'exec'], 2, [1, 2, 1]),
        (['sched', 'exec', 'exec'], 2, [1, 2, 2]),
        (['exec', 'sched', 'exec'], 3, [1, 2, 3]),
        (['sched', 'sched', 'exec'], 2, [2, 1, 2]),
        (['sched', 'sched', 'sched'], 3, [1, 2, 3]),
        (['fresh', 'exec', 'exec'], 2, [1, 2, 1]),
    ]), (17, [      # fresh task first, 2 tenants, one tenant owning both tasks; 3-task shapes below the test sizes
        (['fresh', 'exec'], 2, [1, 1]),
        (['fresh', 'sched'], 2, [1, 1]),
        (['fresh', 'fresh'], 2, [1, 1]),
        (['fresh', 'sched', 'exec'], 2, [1, 2, 1]),
        (['fresh', 'sched', 'sched'], 2, [1, 2, 1]),
    ]), (22, [      # validation: fresh+fresh+exec / fresh+fresh+sched, ownership (1,1,2) and (1,2,2)
        (['fresh', 'fresh', 'exec'], 2, [1, 1, 2]),
        (['fresh', 'fresh', 'sched'], 2, [1, 1, 2]),
        (['fresh', 'fresh', 'exec'], 2, [1, 2, 2]),
        (['fresh', 'fresh', 'sched'], 2, [1, 2, 2]),
    ])],
}


def problem(name, phases, ntenants, owners):
    tasks = [f'task{i + 1}' for i in range(len(phases))]
    tenants = [f'tenant{i + 1}' for i in range(ntenants)]
    L = sum(COST[p] for p in phases)
    desc = ', '.join(f'{t}:{p}' for t, p in zip(tasks, phases))
    own = {t: f'tenant{o}' for t, o in zip(tasks, owners)}
    st = []
    for t, p in zip(tasks, phases):
        st.append([('completed', False), ('validated', False), ('executing', p == 'exec'), ('failed', False),
                   ('scheduled', p == 'sched'), ('rescheduled', False)])
    lit = lambda f, t, v: f'({f} {t})' if v else f'(not ({f} {t}))'
    init = [f'            (submitted {t})' for t in tasks] + ['']
    init += [f'            (not (size-large {t}))' for t in tasks] + ['']
    for t, s in zip(tasks, st):
        init += [f'            {lit(f, t, v)}' for f, v in s]
    ck = [f'                    (submitted {t})' for t in tasks]
    for t, s in zip(tasks, st):
        ck += [f'                    {lit(f, t, v)}' for f, v in s if f != 'validated']
    goal = [f'            (completed {t})' for t in tasks] + [''] + [f'            (validated {t})' for t in tasks] + ['']
    goal += ['            ;; (b) scheduler epistemic closure'] + [f'            ([scheduler] (completed {t}))' for t in tasks] + ['']
    goal += ['            ;; (c) each tenant privately knows its own tasks'] + [f'            ([{own[t]}] (completed {t}))' for t in tasks] + ['']
    goal += ['            ;; (d) privacy: non-owning tenant must not know']
    goal += [f'            (not ([{u}] (completed {t})))' for t in tasks for u in tenants if u != own[t]]
    return f"""{HEADER}
;; Tasks ({desc}); {ntenants} tenants; owners {', '.join(own[t] for t in tasks)}; success path for every task.
;; Estimated minimal plan length: {L}
;;   (fresh=6, sched=4, exec=3 actions per task)
(define (problem {name})

    (:domain cloud-scheduling)

    (:requirements
        :typing
        :facts
        :finitary-S5-theories
        :modal-goals
        :knowing-whether
        :negative-goals
    )

    (:agents scheduler observer reporter {' '.join(tenants)})

    (:objects
        {' '.join(tasks)} - task
    )

    (:facts-init
{chr(10).join(f'        (owner {t} {own[t]})' for t in tasks)}
    )

    (:init
        (:and
{chr(10).join(init)}

            ([C. All]
                (and
{chr(10).join(ck)}
                ))
        )
    )

    (:goal
        (and
            ;; (a) ontic completion + validation
{chr(10).join(goal)}
        )
    )
)
"""


def problems(sets=('v1', 'v2')):
    out = []
    for s in sets:
        for first, specs in SETS[s]:
            for i, (ph, nt, ow) in enumerate(specs, first):
                L = sum(COST[p] for p in ph)
                name = f'g-cloud-{i:02d}-len{L:02d}'
                out.append(Problem(TIER, FAMILY, name, problem(name, ph, nt, ow)))
    return out
