"""Generated search-and-rescue instances (tier 2-intermediate).

Template: the benchmark generator's output (sar-NN-nK-{fire,nofire}): a chain
l0-..-lK, drone D1, firefighter F1 and ambulance A1 all at l0, the victim at
the last location lK (its position not common knowledge), and in the fire
variant a fire at the victim's location (not common knowledge; every other
location is known to be fire-free); goal: rescued-victim. Varied here, keeping
that structure: the chain length, the victim's position (also inside the
chain) and the agents' start locations (common, or one per agent).
Sub-families fire and nofire. Deterministic (no randomness).
"""

from . import Problem

TIER, FAMILY = '2-intermediate', 'search-and-rescue'
# First line of every file (a comment: it is not part of any planner state).
HEADER = ';; Generated by gnn_epddl.generators.search_and_rescue (training/validation instance, not a benchmark problem)'
# (last location index K, victim location, start location(s), intended role); the benchmark has victim = K, start = 0
SPECS = {
    'nofire': [(2, 1, 0, 'train'), (3, 2, 0, 'train'), (2, 2, 1, 'train'), (3, 1, 3, 'train'), (4, 3, 0, 'train'),
               (4, 4, 1, 'train'),
               (5, 4, 0, 'validation'), (5, 5, 0, 'validation'), (5, 5, 1, 'validation'), (6, 5, 0, 'validation')],
    'fire': [(2, 1, 0, 'train'), (3, 1, 0, 'train'), (2, 2, 1, 'train'), (3, 2, 0, 'train'), (3, 3, 1, 'train'),
             (3, 1, 3, 'train'),
             (4, 3, 0, 'validation'), (4, 4, 1, 'validation'), (4, 2, 0, 'validation'), (5, 4, 0, 'validation'),
             # 2-location chain with the agents starting apart (D1 l0, F1 l1, A1 l0): a common start on this chain is
             # one of the instances above, a mirror image of one, or a mirror of a benchmark problem
             (2, 2, (0, 1, 0), 'train')],
}
AG = ['D1', 'F1', 'A1']


def problem(name, K, victim, start, fire):
    starts = list(start) if isinstance(start, tuple) else [start] * 3
    locs = [f'l{i}' for i in range(K + 1)]
    adj = []
    for i in range(K):
        adj += [f'    (adjacent l{i} l{i + 1})', f'    (adjacent l{i + 1} l{i})']
    fires = [f'      (fire-at l{i})' if (fire and i == victim) else f'      (not (fire-at l{i}))' for i in range(K + 1)]
    ckfires = [f'        (not (fire-at l{i}))' for i in range(K + 1) if not (fire and i == victim)]
    uniq = """      (forall (?i - agent ?l1 ?l2 - location | (/= ?l1 ?l2))
        (and
          (imply (at ?i ?l1) (not (at ?i ?l2)))
          (imply (victim-at ?l1) (not (victim-at ?l2)))))"""
    nl = '\n'
    start_txt = ('l' + str(start)) if not isinstance(start, tuple) else ', '.join(f'{a} l{x}' for a, x in zip(AG, starts))
    return f"""{HEADER}
;; Chain l0-..-l{K}; victim at l{victim}; agents start at {start_txt}; fire={'yes' if fire else 'no'}.
(define (problem {name})
  (:domain search-and-rescue)

  (:requirements
    :typing
    :equality
    :facts
    :partial-observability
    :multi-pointed-models
    :modal-goals
    :common-knowledge
    :finitary-S5-theories
    :list-comprehensions
  )

  (:objects
    {' '.join(locs)} - location
  )

  (:agents
    D1
    F1
    A1
  )

  (:facts-init
{nl.join(adj)}

    (is-drone D1)
    (is-ambulance A1)
    (is-firefighter F1)
  )

  (:init
    (:and
{nl.join(f'      (at {a} l{x})' for a, x in zip(AG, starts))}
      (victim-at l{victim})
{nl.join(fires)}
      (not (rescued-victim))

{uniq}

      ([C. All] (and
{nl.join(f'        (at {a} l{x})' for a, x in zip(AG, starts))}
{nl.join(ckfires)}
        (not (rescued-victim))
{uniq.replace(chr(10) + '      ', chr(10) + '        ').replace('      (forall', '        (forall', 1)}
      ))
    )
  )

  (:goal
    (and
      (rescued-victim)
    )
  )
)
"""


def problems():
    out, n = [], 0
    for var in ('nofire', 'fire'):
        for K, v, s, _role in SPECS[var]:
            n += 1
            name = f'g-sar-{n:02d}-n{K}-{var}'
            out.append(Problem(TIER, FAMILY, name, problem(name, K, v, s, var == 'fire')))
    return out
