name: Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set running permissions for scripts
        run: |
          chmod +x ./build.sh

      - name: First compilation and dependencies installation (DEBUG, no onnx, no cuda)
        run: |
          set -e
          sudo ./build.sh install_all debug

      - name: Second compilation (DEBUG, with onnx, no cuda)
        run: |
          set -e
          sudo ./build.sh debug nn no_onnx_test