name: Compilation Check

on:
  push:
    branches: [ main, deep-2.0 ]
  pull_request:
    branches: [ main, deep-2.0 ]
  workflow_dispatch:

jobs:
  compilation:
    name: compilation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set running permissions for scripts
        run: |
          chmod +x ./build.sh

      - name: First compilation and dependencies installation (DEBUG, no onnx, no cuda)
        run: |
          set -e
          ./build.sh install_all debug

      - name: Second compilation (DEBUG, with onnx, no cuda)
        run: |
          set -e
          ./build.sh debug nn no_onnx_test
