name: Execution Check

on:
  push:
    branches: [ main, deep-2.0 ]
  pull_request:
    branches: [ main, deep-2.0 ]
  workflow_dispatch:

jobs:
  execution:
    name: execution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set running permissions for scripts
        run: |
          chmod +x ./build.sh
          chmod +x ./utils/smoke_test.sh
          chmod +x ./utils/onnx_test/run_test.sh

      - name: Install dependencies and compile (RELEASE, with onnx, no cuda)
        run: |
          ./build.sh install_all nn no_onnx_test

      - name: Run minimal onnx check script
        run: |
          ./utils/onnx_test/run_test.sh

      - name: Run EPDDL planning and plan-execution checks
        run: |
          ./utils/smoke_test.sh cmake-build-release-nn/bin/deep
